version: "2"

services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./gitignore:/usr/src/app/gitignore
      - ./package.json:/usr/src/app/package.json
      - ./README.md:/usr/src/app/README.md
    ports:
      - 3000:3000